apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-deployment
  labels:
    app: database-depl

spec:
  replicas: 1

  selector:
    matchLabels:
      app: database

  template:
    metadata:
      labels:
        app: database

    spec:
      containers:
      - name: database-container
        image: mysql:5.7

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: explore123

        - name: MYSQL_DATABASE
          value: exploreworld

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: expo-config
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: expo-config
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: expo-config
              key: DB_USER

        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: expo-config
              key: DB_PASS


        ports:
        - containerPort: 3306
